issue_2 and issue_6 are done!
heyitsalina/ant_search_algorithm pull request #8
Opened 2023-11-30 16:13 UTC by AlhaririAnas

I have created two basic Python files along with their test files for the classes "ant" and "food".

2023-11-30 18:56 UTC, heyitsalina commented
looks good!

2023-12-05 07:29 UTC, honnigmelone requested changes
Would have class-names start with Caps. Apart from that, all looking good,

2023-12-05 07:29 UTC, honnigmelone commented on resources/ant.py
> +class ant:
```suggestion
class Ant:
```

2023-12-05 07:29 UTC, honnigmelone commented on resources/food.py
> +class food:
```suggestion
class Food:
```

2023-12-05 07:29 UTC, honnigmelone commented on test/test_ant.py
> +from resources.ant import *
```suggestion
from resources.Ant import *
```

2023-12-05 07:29 UTC, honnigmelone commented on test/test_food.py
> +from resources.food import *
```suggestion
from resources.Food import *
```

2023-12-05 07:36 UTC, honnigmelone approved these changes

2023-12-05 08:12 UTC, merged